name: CI Pipeline

# Trigger CI on push or pull request to main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job 1: Run Unit & Integration Tests
  unit-integration-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]  # test against Node 18

    steps:
      # Step 1: Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Step 3: Cache Node modules for faster builds
      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 5: Run unit & integration tests using Jest
      - name: Run Unit & Integration Tests
        run: npm test  # assumes "test": "jest" in package.json

      # Step 6: Upload Jest test results (optional)
      - name: Upload Jest Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: jest-report
          path: jest-report/  # make sure jest config outputs here

  # Job 2: Run E2E Tests
  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-integration-tests  # run after unit tests pass

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      # Step: Install Playwright browsers (required)
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step: Run Playwright E2E tests
      - name: Run E2E Tests
        run: npx playwright test  # uses playwright.config.js

      # Step: Upload Playwright HTML report
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/  # must match reporter folder in config
